app:
  host: "127.0.0.1"
  port: 8080
  secret-key: "circle-secret-key"
  log-path: "log/"
  bill-path: "saved-bill/"
  font-asset-path: "lib/asset/font/consola.ttf"
database:
  host: "127.0.0.1"
  port: 3306
  username: "root"
  password: ""
  name: "circle"
redis:
  host: "127.0.0.1"
  port: 6379
  username: ""
  password: ""